### Test GET http://localhost:8080/

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 12:09:54 GMT
Content-Type: text/html
Connection: close
X-uri: /
Content-Length: 592

<html>
<head><title>Index of /</title></head>
<body>
<h1>Index of /</h1><hr><pre><a href="../">../</a>
<a href="Yeah/">Yeah/</a>                                              03-Nov-2021 13:11                   -
<a href="nop/">nop/</a>                                               04-Nov-2021 11:01                   -
<a href="youpi.bad_extension">youpi.bad_extension</a>                                03-Nov-2021 13:11                  45
<a href="youpi.bla">youpi.bla</a>                                          03-Nov-2021 13:11                  35
</pre><hr></body>
</html>

### Test POST http://localhost:8080/ with a size of 0

HTTP/1.1 405 Not Allowed
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 12:13:23 GMT
Content-Type: text/html
Content-Length: 157
Connection: close
X-uri: /

<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

### Test HEAD http://localhost:8080/

HTTP/1.1 405 Not Allowed
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 09:52:03 GMT
Content-Type: text/html
Content-Length: 157
Connection: close
X-uri: /

### Test GET http://localhost:8080/directory

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 14:25:29 GMT
Content-Type: application/octet-stream
Content-Length: 45
Last-Modified: Wed, 03 Nov 2021 13:11:56 GMT
Connection: close
ETag: "61828a9c-2d"
X-uri: /directory/youpi.bad_extension
Accept-Ranges: bytes

This is YoupiBanane/youpi.bad_extension file.

### Test GET http://localhost:8080/directory/youpi.bad_extension

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 12:15:46 GMT
Content-Type: application/octet-stream
Content-Length: 45
Last-Modified: Wed, 03 Nov 2021 13:11:56 GMT
Connection: close
ETag: "61828a9c-2d"
X-uri: /directory/youpi.bad_extension
Accept-Ranges: bytes

This is YoupiBanane/youpi.bad_extension file.

### Test GET http://localhost:8080/directory/youpi.bla

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 12:16:17 GMT
Content-Type: application/octet-stream
Content-Length: 35
Last-Modified: Wed, 03 Nov 2021 13:11:56 GMT
Connection: close
ETag: "61828a9c-23"
X-uri: /directory/youpi.bla
Accept-Ranges: bytes

This is YoupiBanane/youpi.bla file.

### Test GET Expected 404 on http://localhost:8080/directory/oulalala

HTTP/1.1 404 Not Found
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 14:27:09 GMT
Content-Type: text/html
Content-Length: 153
Connection: close
X-uri: /directory/oulalala

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

### Test GET http://localhost:8080/directory/nop

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 14:27:53 GMT
Content-Type: application/octet-stream
Content-Length: 49
Last-Modified: Wed, 03 Nov 2021 13:11:56 GMT
Connection: close
ETag: "61828a9c-31"
X-uri: /directory/nop/youpi.bad_extension
Accept-Ranges: bytes

This is YoupiBanane/nop/youpi.bad_extension file.

### Test GET http://localhost:8080/directory/nop/

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 14:29:38 GMT
Content-Type: application/octet-stream
Content-Length: 49
Last-Modified: Wed, 03 Nov 2021 13:11:56 GMT
Connection: close
ETag: "61828a9c-31"
X-uri: /directory/nop//youpi.bad_extension
Accept-Ranges: bytes

This is YoupiBanane/nop/youpi.bad_extension file.

### Test GET http://localhost:8080/directory/nop/other.pouic

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 12:22:25 GMT
Content-Type: application/octet-stream
Content-Length: 41
Last-Modified: Wed, 03 Nov 2021 13:11:56 GMT
Connection: close
ETag: "61828a9c-29"
X-uri: /directory/nop/other.pouic
Accept-Ranges: bytes

This is YoupiBanane/nop/other.pouic file.

### Test GET Expected 404 on http://localhost:8080/directory/nop/other.pouac

HTTP/1.1 404 Not Found
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 14:31:39 GMT
Content-Type: text/html
Content-Length: 153
Connection: close
X-uri: /directory/nop/other.pouac

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

###  Test GET Expected 404 on http://localhost:8080/directory/Yeah

HTTP/1.1 404 Not Found
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 14:32:54 GMT
Content-Type: text/html
Content-Length: 153
Connection: close
X-uri: /directory/Yeah

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

### Test GET http://localhost:8080/directory/Yeah/not_happy.bad_extension

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 04 Nov 2021 14:36:03 GMT
Content-Type: application/octet-stream
Content-Length: 55
Last-Modified: Wed, 03 Nov 2021 13:11:56 GMT
Connection: close
ETag: "61828a9c-37"
X-uri: /directory/Yeah/not_happy.bad_extension
Accept-Ranges: bytes

This is YoupiBanane/Yeah/not_happy.bad_extension file.

### Test Put http://localhost:8080/put_test/file_should_exist_after with a size of 1000 (1K)

HTTP/1.1 201 Created
Server: nginx/1.20.1
Date: Fri, 05 Nov 2021 10:24:03 GMT
Content-Length: 0
Location: http://localhost/put_test/file_should_exist_after
Connection: close
X-uri: /put_test/file_should_exist_after

### Test Put http://localhost:8080/put_test/file_should_exist_after with a size of 10000000 10M

HTTP/1.1 204 No Content
Server: nginx/1.20.1
Date: Fri, 05 Nov 2021 10:53:07 GMT
Connection: close
X-uri: /put_test/file_should_exist_after

### Test POST http://localhost:8080/directory/youpi.bla with a size of 100000000 (100M)

