Test STATUS_LINE

GET / HTTT/1.1
HTTP/1.1 400 Bad Request

GET HTTP/1.1
HTTP/1.1 400 Bad Request

dfasdfsadfasdf / HTTP/1.1
HTTP/1.1 400 Bad Request

POSTTTTT / HTTP/1/1
HTTP/1.1 400 Bad Request

ASA ** HTTP/1.1
HTTP/1.1 400 Bad Request

GET index.html HTTP/1.1
HTTP/1.1 400 Bad Request

echo -n "GET /index.html HTTP/0" | nc 127.0.0.1 8000
HTTP/1.1 400 Bad Request

GET / HTTP/1.1
dfsdfdsf
dsfsdf
dsfsdf
dsfsdf
dsfsdfdsfds
sdfdsfdsf
sdfdsfsdf
sdsfdsfds
Host: localhost:80

HTTP/1.1 200 OK

GET / HTTP/1.1
Host: localhost
Transfer-Encoding: gzip

HTTP/1.1 501 Not Implemented

POST /post_body HTTP/1.1
Content-type: sdsdsdsd
Host: localhost

HTTP/1.1 200 OK

POST /post_body HTTP/1.1
Content-type: sdsdsdsd
Host: localhost
Content-length: 3

12345
HTTP/1.1 200 OK

HTTP/1.1 400 Bad Request

POST /post_body HTTP/1.1
Host: localhost
Transfer-Encoding: chunked

a
AAAAAAAAAA
0

HTTP/1.1 200 OK

HTTP/1.1 400 Bad RequestAAAAAAAAAA
0

HTTP/1.1 400 Bad Request

POST /post_body HTTP/1.1
Host: localhost
Transfer-Encoding: chunked

3
fff
2
ee
000000000000000000

HTTP/1.1 200 OK
