> A. Invalid request:

>> 1. invalid request line:

dssdfdsf

GETT /

GET / HTT

GET / HTTP/2.0

# tab between
GET	/	HTTP/1.1

CONNECT / HTTP/1.1

>> 2. invalid headers:

GET / HTTP/1.1

>> 3. invalid chunked:

POST /post_body HTTP/1.1
Host: localhost

2
yyyyy


