version: '3'

services:

    #  php:
    #    image: php:8-fpm
    #    container_name: php_c
    #    volumes:
    #      - site_data:/var/www
    #    networks:
    #      - webserv_network
    #    restart : always

  nginx:
    build: nginx
    container_name: nginx_c
    volumes:
      - ${NGINX_DIR}/conf/nginx.conf:/etc/nginx/nginx.conf
      - site_conf:/etc/nginx/conf.d
      - nginx_log:/var/log/nginx
      - site_data:/var/www
      - upload_data:/upload
      - cgi:/cgi
    ports:
        - "80:80"
        - "4242:4242"
        - "4343:4343"
    networks:
      - webserv_network
    restart : always

    #  httpd:
    #    depends_on:
    #      - nginx
    #    build: httpd
    #    container_name: httpd_c
    #    volumes:
    #      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    #      - cgi:/usr/local/apache2/cgi-bin
    #      - YoupiBanane_data:/usr/local/apache2/htdocs/
    #    ports:
    #        - "8080:80"
    #    networks:
    #      - webserv_network
    #    restart : always


volumes:

  site_data:
    name : "site_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/www/"

  upload_data:
    name : "upload_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/upload"

  site_conf:
    name : "site_conf"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINX_DIR}/conf/conf.d"
  
  nginx_log:
    name : "nginx_log"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${LOG_PATH}/nginx"

  cgi:
    name : "cgi"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINX_DIR}/cgi"


networks:

  webserv_network:
    name: "webserv_network"
